### ISSUE TITLE
メッセージを投稿するためのAPIを作成

### ISSUE THREAD

**Issue by nakajima97** [yudai-nakajima/letter-box-backend#8]
# 概要
メッセージを投稿するためのAPIを作成する

# 終了条件
- [x] メッセージを投稿するためのAPIを作成する
~~- [ ] committeeを用いたテストコードを作成し、合格する~~
→postの動作に戸惑い解決に時間かかり中
#9 に切り分ける

# 特記事項
committeeを用いたテストコードが自分の想定通りに進まない
解決に時間がかかると思われるため、#9 に切り分けた

curlを用いた動作確認では想定通りに動作するため、
テストコードをコメントアウトし、無効化した状態でmainにmergeする

これで客側アプリを作成するのに必要なコードはすべて書いた
管理側アプリを作成する前に #9 を解決するようにする

**Comment by nakajima97** [comment]
committeeを用いたテストコードが完成していないが、意図通りに動作しない原因が不明
解決に時間がかかると思われるため、#9 に切りだした

curlを用いた動作確認は済んでいる
### curl動作確認
```bash
❯ curl -X POST -d 'store_id=1&employee_id=1&message_text=test' http://localhost:3000/api/v1/messages/ -o /dev/null -w '%{http_code}\n' -s
201
```

### ログ
```bash
Started POST "/api/v1/messages/" for 172.22.0.1 at 2021-07-02 02:36:36 +0000
   (0.6ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Processing by Api::V1::MessagesController#create as */*
  Parameters: {"store_id"=>"1", "employee_id"=>"1", "message_text"=>"test"}
  TRANSACTION (0.4ms)  BEGIN
  ↳ app/controllers/api/v1/messages_controller.rb:4:in `create'
  Store Load (0.7ms)  SELECT `stores`.* FROM `stores` WHERE `stores`.`id` = 1 LIMIT 1
  ↳ app/controllers/api/v1/messages_controller.rb:4:in `create'
  Employee Load (0.6ms)  SELECT `employees`.* FROM `employees` WHERE `employees`.`id` = 1 LIMIT 1
  ↳ app/controllers/api/v1/messages_controller.rb:4:in `create'
  Message Create (0.6ms)  INSERT INTO `messages` (`store_id`, `employee_id`, `message_text`, `created_at`, `updated_at`) VALUES (1, 1, 'test', '2021-07-02 02:36:37.150781', '2021-07-02 02:36:37.150781')
  ↳ app/controllers/api/v1/messages_controller.rb:4:in `create'
  TRANSACTION (0.8ms)  COMMIT
  ↳ app/controllers/api/v1/messages_controller.rb:4:in `create'
Completed 201 Created in 158ms (Views: 0.6ms | ActiveRecord: 10.9ms | Allocations: 23596)
```

### 実行後DB
いろいろデータがあるが、7/2に追加したコードが上記curlで作成したデータ
```bash
MariaDB [api_development]> select * from messages;
+----+----------+-------------+--------------+----------------------------+----------------------------+
| id | store_id | employee_id | message_text | created_at                 | updated_at                 |
+----+----------+-------------+--------------+----------------------------+----------------------------+
|  1 |        1 |           1 | test         | 2021-07-01 01:11:27.765305 | 2021-07-01 01:11:27.765305 |
|  2 |        1 |           1 | test         | 2021-07-01 01:55:07.369795 | 2021-07-01 01:55:07.369795 |
|  3 |        1 |           1 | test         | 2021-07-01 02:00:20.828410 | 2021-07-01 02:00:20.828410 |
|  4 |        1 |           1 | test         | 2021-07-01 02:06:47.457893 | 2021-07-01 02:06:47.457893 |
|  5 |        1 |           1 | test         | 2021-07-01 02:07:30.042994 | 2021-07-01 02:07:30.042994 |
|  6 |        1 |           1 | test         | 2021-07-02 02:36:37.150781 | 2021-07-02 02:36:37.150781 |
+----+----------+-------------+--------------+----------------------------+----------------------------+
6 rows in set (0.000 sec)
```
