### ISSUE TITLE
rspecで正常なデータをpostで渡したが、2xx以外のデータが返ってくる

### ISSUE THREAD

**Issue by nakajima97** [yudai-nakajima/letter-box-backend#9]
# 概要
#8 をやっている際に発覚した問題
テストで正常なデータをpostを投げているが2xx以外のコードが返ってくる
原因が不明で解決に時間がかかると思われるため、本issueに課題を切り出した

# 終了条件
- [ ] #8 でコメントアウトしたテストコードを動作するようにする

# #8 対応中に発生した問題
### コード
```ruby
class Api::V1::MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    if @message.save
      render status: 201, json: { message: "success" }
    else
      render status: 400, json: { message: "failure" }
    end
  end

  private

  def message_params
    params.permit(:store_id, :employee_id, :message_text)
  end
end
```
### テストコード
```ruby
it "success" do
  post '/api/v1/messages', params: { store_id: 1, employee_id:1, message_text: "test" }
  assert_response_schema_confirm(201)
end
```
### 結果
```bash
Failures:

  1) Api::V1::Messages create messge success
     Failure/Error: assert_response_schema_confirm(201)
     
     Committee::InvalidResponse:
       Expected `201` status code, but it was `400`.
     # /usr/local/bundle/gems/committee-4.4.0/lib/committee/test/methods.rb:32:in `assert_response_schema_confirm'
     # ./spec/requests/api/v1/messages_spec.rb:9:in `block (3 levels) in <main>'
```
### curlの結果
```bash
curl -X POST -d 'store_id=1&employee_id=1&message_text=test' http://localhost:3000/api/v1/messages/ -o /dev/null -w '%{http_code}\n' -s
201
```

curlでは201が返ってくるので、テストコードでのpostの使い方に問題がある

**Comment by nakajima97** [comment]
2023/06/12時点でメンテしていないリポジトリなのでクローズする
